app:
  name: lib-common
  version: v1.0
  host: 127.0.0.1
  port: 8080
  tz: Asia/Shanghai
  secret_key: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
  algorithm: HS256
  access_token_expire: 10 # 分钟
  refresh_token_expire: 3 # 天

loggers:
  common:
    level: DEBUG
    format: "{time:YYYY-MM-DD HH:mm:ss:SSS} | {level: <8} | {process}:{thread} | {name}:{function}:{line} | {message}"
    colorize: false
    serialize: false
    backtrace: true
    enqueue: true
    diagnose: true
    rotation: "10 MB"
    retention: "1 weeks"
    compression: "zip"
    encoding: "utf-8"
    sensitive_fields: (password|token|key|secret|token|session|cookie|csrf|jwt|access_token|refresh_token|id_token|client_secret|client_id|api_key|secret)
    sensitive_fields_replacement: "********"
    max_length: 1000
    max_length_replacement: "..."
  console:
    type: "ConsoleLogger"
    level: "DEBUG"
  run:
    type: "AppLogger"
    level: "DEBUG"
  operate:
    level: "INFO"
  api:
    level: "INFO"

# 加解密器配置
cryptors:
  root:
    salt: 4a8HiqCooyxaevn78tDyPghHrBD7POULoZRN5eTY/e4=


# 数据库配置
databases:
  app:
    type: AsyncSQLAlchemyDB
    infra:
      host: 127.0.0.1
      port: 5432
      username: postgres
      password: hdd12345
    dialect: postgresql
    driver: asyncpg
    database: appc-test
  local:
    type: SQLAlchemyDB
    infra:
      host: 127.0.0.1
      port: 5432
      username: postgres
      password: hdd12345
    dialect: postgresql
    driver: asyncpg
    database: appc-test
  test:
    type: SQLAlchemyDB
    infra:
      host: 127.0.0.1
      port: 5432
      username:
      password:
    dialect: sqlite
    file: ":memory:"
    database: appc-test
    echo: false


redis:
  primary:
    host: "localhost"
    port: 6379
    db: 0

